name: Access server
on: push
jobs:
  access_server:
    name: Access server
    runs-on: ubuntu-latest
    steps:
      - name: Create a file
        uses: appleboy/ssh-action@master
        with:
          host: 13.126.79.22
          username: ec2-user
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            echo hello world > hello.txt
            git init
            git clone https://github.com/sowjiarha/github-ec2connect.git
            git pull origin main
            cd /srv
            pwd
