name: CI/CD
on:
  push:
    branches: main
jobs:
  deploy:
    runs-on: ubutu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy in Ec2
        env:
            PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.HOSTNAME  }}
            USER_NAME : ${{ secrets.USER_NAME  }}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
          
            #Now we have got the access of EC2 and we will start the deploy .
            cd /home/ubuntu/github-ec2connect &&
            git checkout main &&
            git pull origin main &&
            pwd 
          '
