name: Install Ansible
on: push
jobs:
  access_server:
    name: Access server
    runs-on: ubuntu-latest
    steps:
      - name: Create a file
        uses: appleboy/ssh-action@master
        with:
          host: 3.110.166.178
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            sudo apt-add-repository ppa:ansible/ansible
            sudo apt update 
            sudo apt install ansible
