name: Install Ansible
on: push
jobs:
  access_server:
    name: Install Ansible
    runs-on: ubuntu-latest
    steps:
      - name: Install ansible
        uses: appleboy/ssh-action@master
        with:
          host: 3.110.166.178  
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            mkdir scripts
            sudo apt-get update -y
            sudo apt install software-properties-common -y
            sudo add-apt-repository --yes --update ppa:ansible/ansible -y
            sudo apt install ansible -y
            ansible --version 
